{
 "title": "Inverters",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "AC Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "label_replace(sunpower_pvs_inverter_ac_power_watts, \"device_number\", \"$1\", \"device_id\", \"^E[A-Za-z0-9]{9}(.*)\")",
     "legendFormat": "{{device_number}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Heatsink Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sunpower_pvs_inverter_heatsink_temperature_celcius, \"device_number\", \"$1\", \"device_id\", \"E[0-9]{9}(.*)\")",
     "legendFormat": "{{device_number}}"
    }
   ]
  },
  {
   "title": "Panel Efficiency",
   "type": "timeseries",
   "description": "Solar PV Panel Inverters - DC to AC Power  Ratio",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "clamp_min(holt_winters(sunpower_pvs_inverter_ac_power_watts[1h], 0.1, 0.1) / holt_winters(sunpower_pvs_inverter_dc_power_watts[1h], 0.1, 0.1), 0)",
     "legendFormat": "{{ device_id }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}