{
 "title": "Production summary",
 "description": "Solar PV System Summary",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "sunpower-pvs-exporter" }
  ]
 },
 "panels": [
  {
   "title": "Power Consumption vs Production",
   "type": "timeseries",
   "description": "Consumption vs Production - Average Real Power",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(sunpower_pvs_power_meter_average_real_power_watts{mode=\"production\",job=\"$job\"})",
     "legendFormat": "Production",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "sum(sunpower_pvs_power_meter_average_real_power_watts{mode=\"production\",job=\"$job\"})\n+\nsum(sunpower_pvs_power_meter_average_real_power_watts{mode=\"consumption\",job=\"$job\"})",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "Currently Producing",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(sunpower_pvs_power_meter_average_real_power_watts{mode=\"production\",job=\"$job\"})",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Currently Consuming",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sunpower_pvs_power_meter_average_real_power_watts)"
    }
   ]
  },
  {
   "title": "Current Energy Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sunpower_pvs_power_meter_average_real_power_watts{mode=\"consumption\",job=\"$job\"}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Total Production",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sunpower_pvs_power_meter_net_energy_watt_hours{mode=\"production\"}"
    }
   ]
  },
  {
   "title": "Total Consumption",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(sunpower_pvs_power_meter_net_energy_watt_hours{mode=\"consumption\"}) + sum(sunpower_pvs_power_meter_net_energy_watt_hours{mode=\"production\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Energy Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "(sunpower_pvs_power_meter_net_energy_watt_hours{mode=\"consumption\"}/1000)"
    }
   ]
  },
  {
   "title": "Active Solar Panels",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Inverter",
     "crit": 1,
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(sunpower_pvs_device_state{device_type=\"Inverter\",job=\"$job\"})",
     "legendFormat": "Inverter",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}