{
 "title": "PV Supervisor",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (device_id)(sunpower_pvs_supervisor_cpu_loadavg)",
     "legendFormat": "CPU Load Average",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (device_id)(sunpower_pvs_supervisor_mem_used_bytes)",
     "legendFormat": "Memory",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "sum by (device_id)(sunpower_pvs_supervisor_mem_used_bytes) / (1024 * 1024 * 1024)",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (device_id)(rate(sunpower_pvs_supervisor_communication_errors_total[5m]))",
     "legendFormat": "Communication Errors",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "sum by (device_id)(rate(sunpower_pvs_supervisor_errors_total[5m]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum by (device_id)(rate(sunpower_pvs_supervisor_skipped_scans_total[5m]))",
     "legendFormat": "Skipped Scans"
    },
    {
     "expr": "sum by (device_id)(rate(sunpower_pvs_supervisor_untransmitted_events_total[5m]))",
     "legendFormat": "Untransmitted Events"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (device_id)(sunpower_pvs_supervisor_flash_storage_available_bytes)",
     "legendFormat": "Storage",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}